-- ============================================================================
-- ELSA-ERP Database Schema for Supabase
-- Generated from code analysis - 2026-05-28
-- ============================================================================
--
-- This script creates the complete database schema for ELSA-ERP application.
-- No RLS policies are included (to be added separately).
-- No test data is included (structure only).
--
-- ============================================================================

-- ============================================================================
-- TABLE: clientes
-- ============================================================================
-- Stores customer information referenced by solicitudes
-- Columns confirmed from: src/modules/solicitudes/db.js, ClientesScreen.jsx
CREATE TABLE IF NOT EXISTS public.clientes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  nifCif text,
  dirFact text,
  tel text,
  email text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Index for faster lookups by nombre
CREATE INDEX IF NOT EXISTS idx_clientes_nombre ON public.clientes(nombre);

-- ============================================================================
-- TABLE: solicitudes
-- ============================================================================
-- Main table storing service requests/solicitudes
-- Columns confirmed from: src/modules/solicitudes/db.js, FormScreen.jsx
CREATE TABLE IF NOT EXISTS public.solicitudes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Primary identifier
  numero text UNIQUE NOT NULL, -- Format: "S-001", "S-002", etc. Generated by next_solicitud_numero() RPC

  -- Client information (denormalized for convenience, also stored in clientes table)
  cliente text NOT NULL,
  nifCif text,
  dirFact text,
  telCliente text,
  emailCliente text,

  -- Service details
  vehiculo text, -- Comma-separated list of vehicles (e.g. "Grúa 45T, Plataforma")
  origen text,
  destino text,
  descripcion text,

  -- Cargo/Load information (optional)
  metros numeric, -- Square meters of discharge
  peso numeric, -- Weight in kg
  bultos integer, -- Number of packages

  -- Pricing
  precio numeric, -- Estimated price in euros

  -- Photos (JSON array of objects with id, url, path, uploadedAt)
  fotos jsonb DEFAULT '[]'::jsonb,

  -- Status and tracking
  estado text DEFAULT 'pendiente', -- Status: pendiente, en_progreso, completada, cancelada, etc.
  fecha_ultimo_contacto timestamptz DEFAULT now(),

  -- Notes and alerts
  notas_seguimiento jsonb DEFAULT '[]'::jsonb, -- Array of note objects
  avisos_activos boolean DEFAULT true,

  -- Metadata
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_solicitudes_numero ON public.solicitudes(numero);
CREATE INDEX IF NOT EXISTS idx_solicitudes_cliente ON public.solicitudes(cliente);
CREATE INDEX IF NOT EXISTS idx_solicitudes_estado ON public.solicitudes(estado);
CREATE INDEX IF NOT EXISTS idx_solicitudes_created_at ON public.solicitudes(created_at);

-- ============================================================================
-- TABLE: config
-- ============================================================================
-- Singleton table for application configuration
-- Columns confirmed from: src/screens/ConfigScreen.jsx, src/modules/solicitudes/db.js
CREATE TABLE IF NOT EXISTS public.config (
  id integer PRIMARY KEY, -- Always use id=1

  -- Company information
  nombre text,
  tel text,
  email text,
  direccion text,
  logo text, -- Base64-encoded image data or data URL

  -- Configuration lists (stored as JSON arrays)
  vehicles jsonb, -- Array of vehicle/equipment types (e.g. ["Grúa 45T", "Plataforma", ...])
  workTypes jsonb, -- Array of work types (reserved for future use, not currently saved in code)

  -- Metadata
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================================================
-- TABLE: _solicitud_counter
-- ============================================================================
-- Internal table to track the next solicitud number for the RPC function
-- This ensures sequential, non-colliding numbers across concurrent inserts
CREATE TABLE IF NOT EXISTS public._solicitud_counter (
  id integer PRIMARY KEY DEFAULT 1,
  next_number integer DEFAULT 1,
  updated_at timestamptz DEFAULT now()
);

-- Initialize counter
INSERT INTO public._solicitud_counter (id, next_number)
VALUES (1, 1)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- RPC FUNCTION: next_solicitud_numero
-- ============================================================================
-- Generates the next sequential solicitud number in format "S-XXX"
-- Called by dbSaveSolicitud in src/modules/solicitudes/db.js
--
-- Example output: "S-001", "S-002", ..., "S-999", "S-1000", etc.
--
-- ASSUMPTIONS:
-- - Format is hardcoded as "S-" prefix with zero-padded number (initially)
-- - Not strictly zero-padded after 999 (becomes "S-1000" without leading zeros)
-- - Counter persists across application restarts (stored in _solicitud_counter)
--
CREATE OR REPLACE FUNCTION public.next_solicitud_numero()
RETURNS text AS $$
DECLARE
  next_num integer;
BEGIN
  -- Increment counter and get the new value atomically
  UPDATE public._solicitud_counter
  SET next_number = next_number + 1,
      updated_at = now()
  WHERE id = 1
  RETURNING next_number INTO next_num;

  -- Format as "S-XXX" (or "S-XXXX" for numbers >= 1000)
  RETURN 'S-' || LPAD(next_num::text, 3, '0');
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- NOTES AND ASSUMPTIONS
-- ============================================================================
--
-- COLUMN TYPES - Assumptions made:
--
-- 1. solicitudes.numero (text)
--    - Confirmed: Generated by next_solicitud_numero() RPC
--    - Assumption: Format is "S-001", "S-002", etc.
--    - Should verify actual format preference if different (e.g., "-001", "SOL-001")
--
-- 2. solicitudes.vehiculo (text)
--    - Confirmed: Stored as comma-separated string (see sanitize() in db.js line 4-7)
--    - Alternative: Could be jsonb array instead of text
--
-- 3. solicitudes.fotos (jsonb)
--    - Deduced: Array of photo objects with {id, url, path, uploadedAt}
--    - Storage: Photos are actually stored in Supabase Storage bucket "service-photos"
--    - This column stores metadata/references only, not actual files
--
-- 4. solicitudes.notas_seguimiento (jsonb)
--    - Confirmed: Array of note objects (see dbAddNota in db.js)
--    - Assumption: Each note contains at least text, user, timestamp
--    - Should verify exact structure of note objects
--
-- 5. solicitudes.estado (text)
--    - Confirmed: Has at least values "pendiente"
--    - Assumption: Other states might be "completada", "cancelada", "en_progreso"
--    - Should verify all possible estado values and consider ENUM type
--
-- 6. solicitudes.avisos_activos (boolean)
--    - Confirmed: Boolean toggle (see dbToggleAvisos in db.js line 77-79)
--    - Default: true
--
-- 7. solicitudes.metros, peso, bultos (numeric/integer)
--    - Confirmed: Parsed as numbers but optional (line 16-18 in db.js)
--    - Assumption: metros and peso are decimal (numeric), bultos is integer
--
-- 8. config.vehicles, workTypes (jsonb)
--    - Confirmed: Arrays of strings
--    - vehicles: Used to populate form buttons in FormScreen.jsx
--    - workTypes: Defined in constants but not currently persisted (verify if needed)
--
-- RLS POLICIES:
-- Currently disabled. When enabling:
-- - clientes: Should restrict to auth.uid() owner or authenticated users
-- - solicitudes: Should restrict to auth.uid() owner or authenticated users
-- - config: Typically read-only for authenticated users, write-only for admin
-- - _solicitud_counter: Should deny direct access (internal use only)
--
-- FUTURE CONSIDERATIONS:
-- - Consider ENUM type for solicitudes.estado (pendiente, completada, etc.)
-- - Consider separate table for notas if querying by note is frequent
-- - Consider audit/changelog table for tracking solicitud changes
-- - Consider adding created_by, updated_by fields for accountability
-- - Estado values should be documented and enforced with constraints
--
-- ============================================================================
